enum Events {
    EVT_PUZZLE_REMOVE_CELL = 'EVT_PUZZLE_REMOVE_CELL',
    EVT_PUZZLE_GAME_OVER = 'EVT_PUZZLE_GAME_OVER',

    EVT_PUSHTRAIN_CONFIRM_OK_CLICKED = 'EVT_PUSHTRAIN_CONFIRM_OK_CLICKED',
    EVT_PUSHTRAIN_CONFIRM_CANCEL_CLICKED = 'EVT_PUSHTRAIN_CONFIRM_CANCEL_CLICKED',
}

export = Events