enum Events {
    EVT_PUZZLE_REMOVE_CELL = 'EVT_PUZZLE_REMOVE_CELL',
    EVT_PUZZLE_GAME_OVER = 'EVT_PUZZLE_GAME_OVER',
    EVT_DIAMOND_TIMEOUT = 'EVT_DIAMOND_TIMEOUT',
    EVT_DIAMOND_START_WARNING = 'EVT_DIAMOND_START_WARNING',
    EVT_DIAMOND_STOP_WARNING = 'EVT_DIAMOND_STOP_WARNING',
}

export = Events